name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1 

      with:

          username: ${{ secrets.DOCKER_USERNAME }}

          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 


    - uses: docker/build-push-action@v2

      with:

          context: ./

          file: ./Dockerfile

          push: true

          tags: nurakmed/yogaashram:latest

  run: echo ${{ steps.docker_build.outputs.digest }}

        
