name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      
    - name: Build and push docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nurakmed/yogaashram:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  

        
